# Generated by Django 4.2.1 on 2023-06-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RunSQL("""
         INSERT INTO store_collection (title)
         VALUES ('collection1')
         """,""" 
         DELETE FROM store_collection
         WHERE title='collection1'
         """)
    ]
